[project]
name = "farewell-rss"
dynamic = ["version"]
description = "我到现在终于没有见——大约 RSS 的确死了。"
readme = "README.md"
authors = [
    { name = "轩哥有内涵"}
]
requires-python = ">=3.14"
urls = { Repository = "https://github.com/xuangeyouneihan/FarewellRSS" }
dependencies = [
    "aiosqlite>=0.22.1",
    "bcrypt>=5.0.0",
    "fastapi>=0.139.0",
    "feedparser>=6.0.12",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.0.51",
    "uvicorn[standard]>=0.51.0",
    "winuvloop>=0.2.4",
]

[project.scripts]
farewell-rss = "farewell_rss:main"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build]
dev-mode-dirs = ["src"]

[tool.hatch.build.targets.wheel]
packages = ["src/farewell_rss"]

[tool.pytest.ini_options]
asyncio_mode = "auto"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-cov>=7.1.0",
    "pytest-xdist>=3.8.0",
]
